// export const countryCodes = [
//     { country: 'India', code: '+91' },
//     { country: 'USA', code: '+1' },
//     { country: 'UK', code: '+44' },
//     { country: 'Canada', code: '+1' },
//     { country: 'Australia', code: '+61' },
//     { country: 'Germany', code: '+49' },

// ];


export const countryCodes = [
    { "country": "India", "code": "+91" },
    { "country": "USA", "code": "+1" },
    { "country": "UK", "code": "+44" },
    { "country": "Canada", "code": "+1" },
    { "country": "Australia", "code": "+61" },
    { "country": "Germany", "code": "+49" },
    { "country": "Afghanistan", "code": "+93" },
    { "country": "Albania", "code": "+355" },
    { "country": "Algeria", "code": "+213" },
    { "country": "Andorra", "code": "+376" },
    { "country": "Angola", "code": "+244" },
    { "country": "Antigua and Barbuda", "code": "+1-268" },
    { "country": "Argentina", "code": "+54" },
    { "country": "Armenia", "code": "+374" },
    { "country": "Austria", "code": "+43" },
    { "country": "Azerbaijan", "code": "+994" },
    { "country": "Bahamas", "code": "+1-242" },
    { "country": "Bahrain", "code": "+973" },
    { "country": "Bangladesh", "code": "+880" },
    { "country": "Barbados", "code": "+1-246" },
    { "country": "Belarus", "code": "+375" },
    { "country": "Belgium", "code": "+32" },
    { "country": "Belize", "code": "+501" },
    { "country": "Benin", "code": "+229" },
    { "country": "Bhutan", "code": "+975" },
    { "country": "Bolivia", "code": "+591" },
    { "country": "Bosnia and Herzegovina", "code": "+387" },
    { "country": "Botswana", "code": "+267" },
    { "country": "Brazil", "code": "+55" },
    { "country": "Brunei", "code": "+673" },
    { "country": "Bulgaria", "code": "+359" },
    { "country": "Burkina Faso", "code": "+226" },
    { "country": "Burundi", "code": "+257" },
    { "country": "Cabo Verde", "code": "+238" },
    { "country": "Cambodia", "code": "+855" },
    { "country": "Cameroon", "code": "+237" },
    { "country": "Central African Republic", "code": "+236" },
    { "country": "Chad", "code": "+235" },
    { "country": "Chile", "code": "+56" },
    { "country": "China", "code": "+86" },
    { "country": "Colombia", "code": "+57" },
    { "country": "Comoros", "code": "+269" },
    { "country": "Congo (Congo-Brazzaville)", "code": "+242" },
    { "country": "Congo (Democratic Republic)", "code": "+243" },
    { "country": "Costa Rica", "code": "+506" },
    { "country": "Croatia", "code": "+385" },
    { "country": "Cuba", "code": "+53" },
    { "country": "Cyprus", "code": "+357" },
    { "country": "Czech Republic (Czechia)", "code": "+420" }
];
